apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-job
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/amar-chand/argo-kubernetes-job'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
